title: "Direction Qibla - Trouvez la Mecque"
description: "Application web gratuite pour trouver la direction de la Qibla (La Mecque) depuis votre position GPS avec une carte interactive."
lang: fr
url: "https://mohamedehj.github.io"
author: "Mohamed EHJ"

# SEO
google_analytics: # Ajoutez votre ID Google Analytics ici si vous en avez un
